# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaAttic < Formula
  desc "Read-only scanner that quantifies unused Kafka topics with the ATTIC Score"
  homepage "https://github.com/sderosiaux/kafka-attic"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sderosiaux/kafka-attic/releases/download/v0.1.0/kafka-attic_0.1.0_darwin_amd64.tar.gz"
      sha256 "e7c459dac490cdb75b624a6df49961d8d43e6c82791bbe7d3086066acd4d8769"

      define_method(:install) do
        bin.install "kattic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sderosiaux/kafka-attic/releases/download/v0.1.0/kafka-attic_0.1.0_darwin_arm64.tar.gz"
      sha256 "9b69b90e323dfe6671a95657ee4c06cfa014399d7d1a2fbc9579d8e163dd76cf"

      define_method(:install) do
        bin.install "kattic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sderosiaux/kafka-attic/releases/download/v0.1.0/kafka-attic_0.1.0_linux_amd64.tar.gz"
      sha256 "1e83b4a268be4d1f777e1122065e972cbf944e73417dfc3a1bb4a5012771dd0f"
      define_method(:install) do
        bin.install "kattic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sderosiaux/kafka-attic/releases/download/v0.1.0/kafka-attic_0.1.0_linux_arm64.tar.gz"
      sha256 "685467a1d21c72690336a823f44414c4333c4b21b3c2c995eea9eb76a6411fe8"
      define_method(:install) do
        bin.install "kattic"
      end
    end
  end

  test do
    system "#{bin}/kattic", "--version"
  end
end
